FROM python:3.11-slim

EXPOSE 8001

WORKDIR /workspace/backend

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY python/requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"

ENV PYTHONPATH=/workspace/backend/python
ENV DJANGO_SETTINGS_MODULE=django_app.settings