services:
  mongodb:
    image: mongo:8.0
    container_name: interneers_lab_2026_mongodb
    ports:
      - '27019:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: ..
      dockerfile: python/Dockerfile.dev
    container_name: interneers_lab_2026_app
    ports:
      - '8000:8001'
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASS: example
      MONGO_DB: inventory
      MONGO_AUTH_SOURCE: admin
    volumes:
      - ..:/workspace/backend
    depends_on:
      - mongodb
    command: python manage.py runserver 0.0.0.0:8001

volumes:
  mongodb_data:
